
service: react-ionic-pwa-server

package:
  include:
    - public
    - server
    - package.json
  ignore:
    - secrets.yml
  excludeDevDependencies: false

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    NODE_ENV: "${self:custom.secrets.NODE_ENV, 'production'}"
    AUTH_SECRET: "${self:custom.secrets.AUTH_SECRET, env:AUTH_SECRET}"
    MONGO_URL: "${self:custom.secrets.MONGO_URL, env:MONGO_URL}"
    FCM_KEY: "${self:custom.secrets.FCM_KEY, env:FCM_KEY}"
    PASSWORD_SALT_ITERATIONS: "${self:custom.secrets.PASSWORD_SALT_ITERATIONS, '14'}"
    TRANSPORT_AUTH: "${self:custom.secrets.TRANSPORT_AUTH, env:TRANSPORT_AUTH}"

custom:
  secrets: ${file(./secrets.yml):${self:provider.stage}}
  defaultStage: dev
  apigwBinary:
    types:
      - 'image/png'
      - 'image/x-icon'
      - 'image/*'

functions:
  server:
    handler: serverlessIndex.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-apigw-binary
  - serverless-offline